accumulate_grad_batches: 1
amp: false
aux_l1_loss: true
aux_percep_loss: false
aux_ssim_loss: false
base_config:
- ./diffsr_base.yaml
- ./lfsr4x.yaml
batch_size: 4
beta_end: 0.02
beta_s: 0.008
beta_schedule: cosine
binary_data_dir: data/binary/lfsr4x
check_val_every_n_epoch: 10
clip_grad_norm: 10
clip_input: true
crop_size: 640
data_augmentation: false
data_interp: bicubic
debug: false
decay_steps: 100000
denoise_fn: unet
ds_workers: 1
enc_ckpt: checkpoints/epit_y_lfsr4x_c32_bs4
enc_fn: epit
enc_num_block: 8
enc_num_feat: 32
endless: false
eval_batch_size: 1
fix_enc: true
gen_dir_name: 4X
gn_groups: 0
hidden_size: 32
infer: false
load_ckpt: ''
loss_type: l1
lr: 0.0002
max_epochs: 1000
max_updates: 200000
num_ckpt_keep: 100
num_sanity_val_steps: 4
num_workers: 2
patch_size: 640
pred_noise: true
print_arch: false
print_nan_grads: false
res: true
res_rescale: 2.0
resume_from_checkpoint: 0
save_best: true
save_codes:
- configs
- models
- tasks
- utils
save_intermediate: false
seed: 42
show_training_process: false
sr_scale: 4
style_interp: false
tb_log_interval: 100
test_batch_size: 1
test_crop_size:
- 8000
- 8000
test_input_dir: ''
test_save_png: true
test_thresh_size: 0
thresh_size: 0
timesteps: 100
trainer_cls: tasks.srdiff_lfsr.SRDiffLFSR
unet_dim_mults: 1|1|1|1
up_input: false
use_attn: false
use_distgunet: true
use_enc: true
use_wn: false
val_check_interval: 10000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_steps: 4
weight_init: false
work_dir: checkpoints/diffsr_epit_distgunet_m1111_lfsr4x_c32_bs4
