accumulate_grad_batches: 1
amp: false
base_config:
- ../sr_base.yaml
- ../lfsr4x.yaml
batch_size: 4
binary_data_dir: data/binary/lfsr4x
check_val_every_n_epoch: 10
clip_grad_norm: 0
crop_size: 640
data_augmentation: false
data_interp: bicubic
debug: false
ds_workers: 1
endless: false
eval_batch_size: 1
gen_dir_name: 4X
hidden_size: 32
infer: false
load_ckpt: ''
lr: 0.0002
max_epochs: 1000
max_updates: 200000
num_ckpt_keep: 100
num_sanity_val_steps: 4
num_workers: 2
patch_size: 640
print_nan_grads: false
resume_from_checkpoint: 0
save_best: true
save_codes:
- configs
- models
- tasks
- utils
save_intermediate: false
seed: 42
sr_scale: 4
tb_log_interval: 100
test_batch_size: 1
test_crop_size:
- 8000
- 8000
test_input_dir: ''
test_save_png: true
test_thresh_size: 0
thresh_size: 0
trainer_cls: tasks.epit.EPITLFSRTask
val_check_interval: 4000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_steps: 4
work_dir: checkpoints/epit_y_lfsr4x_c32_bs4
