base_config:
  - ./config_base.yaml
  - ./sr_base.yaml
# model
beta_schedule: cosine
beta_s: 0.008
beta_end: 0.02
hidden_size: 32 # 64 
timesteps: 100
res: true # whether use residual: model learn to residual
res_rescale: 2.0 # scale residual ratio
up_input: false # whether up scale input
use_wn: false
gn_groups: 0
use_enc: true # true
enc_num_block: 8 # no use
enc_num_feat: 32 # 64 # enc hidden channel
enc_ckpt: ''
unet_dim_mults: 1|2|2|4
clip_input: true # why?
denoise_fn: unet
use_attn: false
aux_l1_loss: true
aux_ssim_loss: false
aux_percep_loss: false
loss_type: l1
pred_noise: true # no use
clip_grad_norm: 10
weight_init: false
fix_enc: true

# train and eval
lr: 0.0002
decay_steps: 100000
accumulate_grad_batches: 1 # no use
style_interp: false # no use
save_intermediate: false
show_training_process: false # no use
print_arch: false # no use
