base_config:
  - ./diffsr_base.yaml
  - ./lfsr8x.yaml
trainer_cls: tasks.srdiff_lfsr.SRDiffLFSR

val_check_interval: 10000
enc_num_feat: 32
hidden_size: 32

# model
unet_dim_mults: 1|1|1|1 # 1|1|2|2
decay_steps: 100000
use_distgunet: true # true

# train and test
lr: 0.0001 # 0.0002
batch_size: 1
max_updates: 400000

### test setting
test_save_png: true
save_intermediate: false 
gen_dir_name: '8X'

enc_fn: "epit"
enc_ckpt: checkpoints/epit_y_lfsr8x_c32_bs4
fix_enc: true