base_config: ./config_base.yaml
data_interp: bicubic # bilinear | bicubic
data_augmentation: false # whether use data_augmentation
max_updates: 300000
batch_size: 16
eval_batch_size: 1
test_batch_size: 1
valid_steps: 3 # test number = valid_steps * eval_batch_size
num_sanity_val_steps: 3 # the number of first evaluate
test_save_png: false # whether save img when test process
gen_dir_name: ''